[package]
name = "Bitmesh"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
bip39 = "2.2.2"
breez-sdk-spark = { git = "https://github.com/breez/spark-sdk", tag = "0.6.1" }
dotenv = "0.15.0"
ethers = "2.0.14"
rand = "0.9.2"
thiserror = "2.0.17"
tokio = "1.48.0"

[workspace]
